name: Build and Test

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
      
    - name: Set up .NET
      uses: actions/setup-dotnet@v5
      with: 
        dotnet-version: '10.0'
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build C# Application
      run: dotnet build --no-restore
      
    - name: Run tests
      run: dotnet test --no-build --verbosity normal
    
